#!/usr/bin/env node

import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import { SynapseRunner } from './runner';
import { ConfigValidator } from './validators/configValidator';

const program = new Command();

program
  .name('synapse')
  .description('Dynamic load testing tool using K6')
  .version('1.0.0');

program
  .command('run')
  .description('Run load test from configuration file')
  .option('-c, --config <path>', 'Path to configuration file', 'synapse.yml')
  .option('-o, --output <path>', 'Output directory for generated files', './output')
  .option('--dry-run', 'Generate K6 script without running the test')
  .option('--keep-script', 'Keep generated K6 script after test completion')
  .action(async (options) => {
    try {
      console.log(chalk.blue('🔄 Starting Synapse Load Test...'));
      
      const configPath = path.resolve(options.config);
      if (!fs.existsSync(configPath)) {
        console.error(chalk.red(`❌ Configuration file not found: ${configPath}`));
        process.exit(1);
      }

      const runner = new SynapseRunner();
      await runner.run(configPath, {
        outputDir: options.output,
        dryRun: options.dryRun,
        keepScript: options.keepScript
      });

    } catch (error) {
      console.error(chalk.red('❌ Error:'), error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

program
  .command('validate')
  .description('Validate configuration file')
  .option('-c, --config <path>', 'Path to configuration file', 'synapse.yml')
  .action(async (options) => {
    try {
      const configPath = path.resolve(options.config);
      if (!fs.existsSync(configPath)) {
        console.error(chalk.red(`❌ Configuration file not found: ${configPath}`));
        process.exit(1);
      }

      const validator = new ConfigValidator();
      const isValid = await validator.validateFile(configPath);
      
      if (isValid) {
        console.log(chalk.green('✅ Configuration is valid'));
      } else {
        console.error(chalk.red('❌ Configuration validation failed'));
        process.exit(1);
      }
    } catch (error) {
      console.error(chalk.red('❌ Error:'), error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

program
  .command('init')
  .description('Initialize a new Synapse configuration file')
  .option('-n, --name <name>', 'Test name', 'My Load Test')
  .option('-u, --url <url>', 'Base URL', 'https://api.example.com')
  .action((options) => {
    const template = `name: "${options.name}"
description: "Generated by Synapse CLI"
baseUrl: "${options.url}"

execution:
  mode: "construct"
  concurrent: 10
  iterations: 100

parameters:
  - name: "id"
    type: "integer"
    min: 1
    max: 1000

k6Options:
  thresholds:
    http_req_duration: ["p(95)<500"]

request:
  method: "GET"
  headers:
    "User-Agent": "Synapse Load Tester"
`;

    fs.writeFileSync('synapse.yml', template);
    console.log(chalk.green('✅ Created synapse.yml configuration file'));
    console.log(chalk.blue('💡 Edit the file and run: synapse run'));
  });

program
  .command('generate')
  .description('Generate K6 script from configuration without running')
  .option('-c, --config <path>', 'Path to configuration file', 'synapse.yml')
  .option('-o, --output <path>', 'Output file for K6 script', 'test.js')
  .action(async (options) => {
    try {
      const runner = new SynapseRunner();
      await runner.generateScript(options.config, options.output);
      console.log(chalk.green(`✅ K6 script generated: ${options.output}`));
    } catch (error) {
      console.error(chalk.red('❌ Error:'), error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

program
  .command('test')
  .description('Run simple load test without configuration file')
  .requiredOption('-u, --url <url>', 'Target URL to test')
  .requiredOption('-c, --concurrent <number>', 'Number of concurrent users')
  .requiredOption('-r, --requests <number>', 'Total number of requests')
  .option('-o, --output <path>', 'Output directory for results', './output')
  .option('--dry-run', 'Generate K6 script without running the test')
  .option('--keep-script', 'Keep generated K6 script after test completion')
  .action(async (options) => {
    try {
      console.log(chalk.blue('🔄 Starting Simple Load Test...'));
      
      const runner = new SynapseRunner();
      await runner.runSimpleTest({
        url: options.url,
        concurrent: parseInt(options.concurrent),
        requests: parseInt(options.requests),
        outputDir: options.output,
        dryRun: options.dryRun,
        keepScript: options.keepScript
      });

    } catch (error) {
      console.error(chalk.red('❌ Error:'), error instanceof Error ? error.message : error);
      process.exit(1);
    }
  });

program.parse();
